In [4]:
import numpy as np

a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
mask = (a>=5) & (a<=10)
a[mask]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
mask_a = np.logical_and(a>=5,a<=10)
a[mask_a]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
mask_b == 